CREATE TABLE IF NOT EXISTS FILMS
(
 FILM_ID INT PRIMARY KEY AUTO_INCREMENT,
 FILM_NAME VARCHAR(255),
 DESCRIPTION VARCHAR(255),
 RELEASE_DATE DATE,
 DURATION INT,
 MPA_ID INT
);

CREATE TABLE IF NOT EXISTS GENRE
(
 GENRE_ID INT PRIMARY KEY AUTO_INCREMENT,
 GENRE_NAME VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS FILM_GENRE
(
 FILM_GENRE_ID INT PRIMARY KEY AUTO_INCREMENT,
 GENRE_ID INT,
 FILM_ID INT
);

CREATE TABLE IF NOT EXISTS MPA
(
 MPA_ID INT PRIMARY KEY AUTO_INCREMENT,
 NAME_MPA VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS USERS
(
 USER_ID INT PRIMARY KEY AUTO_INCREMENT,
 EMAIL VARCHAR(255),
 LOGIN VARCHAR(255),
 USER_NAME VARCHAR(255),
 BIRTHDAY DATE
);

CREATE TABLE IF NOT EXISTS STATUS_FRIEND
(
 STATUS_FRIEND_ID INT PRIMARY KEY AUTO_INCREMENT,
 USER_ID INT,
 FRIEND_ID INT
);

CREATE TABLE IF NOT EXISTS FILM_LIKE
(
 FILM_LIKE_ID INT PRIMARY KEY AUTO_INCREMENT,
 FILM_ID INT,
 USER_ID INT
);

ALTER TABLE FILM_GENRE ADD FOREIGN KEY (GENRE_ID) REFERENCES GENRE (GENRE_ID);

ALTER TABLE FILM_GENRE ADD FOREIGN KEY (FILM_ID) REFERENCES FILMS (FILM_ID);

ALTER TABLE FILMS ADD FOREIGN KEY (MPA_ID) REFERENCES MPA (MPA_ID);

ALTER TABLE STATUS_FRIEND ADD FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID);

ALTER TABLE STATUS_FRIEND ADD FOREIGN KEY (FRIEND_ID) REFERENCES USERS (USER_ID);

ALTER TABLE FILM_LIKE ADD FOREIGN KEY (FILM_ID) REFERENCES FILMS (FILM_ID);

ALTER TABLE FILM_LIKE ADD FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID);
